### ISSUE TITLE
Index4 Issue 

### ISSUE THREAD

**Issue by Gevonw97** [Gevonw97/Gevonw97.github.io#5]
In the file the code looks perfect but when I go to the browser to see it, it does not display horizontally but displays vertically.

**Comment by landrykapela** [comment]
Hey, I can see you forgot to close the `div` with id left-side so the right-side `div` fell inside the left-side one. Check that and you can close this issue. By the way, why is this issue #5 while there's only 1 issue?

**Comment by Gevonw97** [comment]
Lol it placed the number 5 next to it.

**Comment by landrykapela** [comment]
Why is this issue still open?
