### ISSUE TITLE
Profile image not displaying

### ISSUE THREAD

**Issue by landrykapela** [Gevonw97/Gevonw97.github.io#7]
I can't get the image to display when I run the html from my pc. I can't see the image file you referred to in the repo (`<img src="pictures/IMG-0910.jpg" alt="Von" class="profile-image" /> `). Please check that and delete the older files. That is why we have VCS anyway!

**Comment by Gevonw97** [comment]
I needed help setting up the VCS I do not know how to connect my account. Also the image should work if not I need more insight on how to fix this issue.
